### ISSUE TITLE
为什么第二个域名不好使

### ISSUE THREAD

**Issue by SERE026** [FastTunnel/FastTunnel#18]
![image](https://user-images.githubusercontent.com/14211349/106093145-b077c900-616a-11eb-8f1f-f7cb011a28c4.png)

![image](https://user-images.githubusercontent.com/14211349/106092829-11eb6800-616a-11eb-8042-028ba4b3ca16.png)
![image](https://user-images.githubusercontent.com/14211349/106092873-292a5580-616a-11eb-8956-1946bdddbc97.png)

**Comment by SpringHgui** [comment]
找到原因了吗，能重现这个问题吗

**Comment by SERE026** [comment]
没找到

**Comment by SpringHgui** [comment]
1. 这个域名没有问题
2. invalid Host header 应该是你的内网站点返回的内容，请检查你后端检查header内容时为什么返回这个错误，再进一步排查
3. 你试试用 http://h5.sh1.k9s.run:2270/ 访问，看看是否有同样的问题，不加端口访问的话，服务端反向代理时可能丢掉了部分header的内容
