### ISSUE TITLE
请教一下，开启远程桌面端口，远程连接时客户端就是会退出登陆，要求重新登陆！！！

### ISSUE THREAD

**Issue by copywater** [FastTunnel/FastTunnel#22]
测试开启远程桌面端口，远程连接时客户端就是会退出登陆，要求重新登陆！！！

**Comment by SpringHgui** [comment]
把你的登陆后客户端显示的映射信息，以及你远程桌面的ip地址截图发下

**Comment by copywater** [comment]
> 把你的登陆后客户端显示的远程地图信息，以及你桌面的ip地址截图发下

能加您的QQ吗？
通过QQ发给您

**Comment by copywater** [comment]
之前是下载编译好的客户端直接运行出现问题，这次下载了源码调试运行，没有出现客户端退出问题！

**Comment by SpringHgui** [comment]
解决了就好

**Comment by copywater** [comment]
> 解决了就好

谢谢
