### ISSUE TITLE
identity

### ISSUE THREAD

**Issue by tinamore** [FastTunnel/FastTunnel#29]
First, Thank for great project
I've been looking for a tunnel tool that supports .net for a long time, and now it seems I've found it
I have a question:  client identity verification => this is check account user/pass when connect server ?
![image](https://user-images.githubusercontent.com/2157845/127431828-4494b9e8-280d-4308-a880-cf3680f13b1b.png)
I'm deploying to a client, but I'm worried others can connect freely without a user/pass
Thanks

**Comment by SpringHgui** [comment]
Use [AuthenticationFilter](https://github.com/FastTunnel/FastTunnel/blob/master/FastTunnel.Server/Filters/TestAuthenticationFilter.cs)

**Comment by tinamore** [comment]
Thankyou very much!

**Comment by tinamore** [comment]
Can you give code example for add (user/pass/token) in client and check Authentication in server ?
This library is important for me, to implement https to localhost via nginx let's encypt !

**Comment by SpringHgui** [comment]
https  has not support yet.
check authentication is not supported for https.

**Comment by tinamore** [comment]
I still use http (forward to http to https via nginx, not at server tunnel).
Can you help me example code for Authentication  !

**Comment by SpringHgui** [comment]
I has add Token feild in configs，you can use directly.
[server config](https://github.com/FastTunnel/FastTunnel/blob/master/FastTunnel.Server/config/appsettings.json)
[server config](https://github.com/FastTunnel/FastTunnel/blob/master/FastTunnel.Client/appsettings.json)

**Comment by tinamore** [comment]
Thank for support,
I have a better understanding of the dotnet structure.
